export function resizeListener(): void;
export function logoutOut(navigate: any): void;
export function phoneEncryption(phone: any): any[];
export function idEncryption(id: any): any;
export function jsonString(str: any): any;
export function replaceString(str: any): any;
export function dateFormatter(str: any): string;
export function truncateText(text: any): any;
export function transformDate(value: any, dataLabel: any): import("lodash").Dictionary<string | null>;
export function toFixed(num: any): string;
